version: "3"

services:

 app:
  image: 1510008147/tcc-docker:1.0
  deploy:
    mode: replicated
    replicas: 1 
    restart_policy:
      condition: on-failure
      delay: 3s
    resources:
      limits:
        cpus: "0.10"
        memory: "50M"
  ports:
    - "80:80" 
  networks:
    - webnet

networks:
 webnet:
 
