version: "3"

services:

 webapp:
  image: 1510008147/docker-01:1.0
  deploy:
    mode: replicated
    replicas: 10 
    restart_policy:
      condition: on-failure
      delay: 3s
    resources:
      limits:
        cpus: "0.10"
        memory: "50M"
  ports:
    - "80:80" 
  networks:
    - webnet

networks:
 webnet:
 
