version: "3"

services:

 app-one:
  image: 1510008147/my-image-one:1.0
  deploy:
    mode: replicated
    replicas: 4 
    restart_policy:
      condition: on-failure
      delay: 1s
  ports:
    - "80:80" 
  networks:
    - webnet

 app-two:
  image: 1510008147/my-image-two:1.0
  deploy:
    mode: replicated
    replicas: 4 
    restart_policy:
      condition: on-failure
      delay: 1s
  ports:
    - "8080:80" 
  networks:
    - webnet

networks:
 webnet:
 
